open -a TextEdit supabase/schema.sqlcreate extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  access_token text not null unique,
  status text not null default 'pending_payment' check (status in ('pending_payment', 'paid', 'processing', 'completed', 'failed', 'retryable')),
  delivery_status text not null default 'not_sent',
  plan text not null,
  amount_aed numeric(10,2) not null default 0,
  full_name text not null,
  email text not null,
  target_role text not null,
  target_country text not null,
  job_description text,
  original_file_name text,
  original_file_path text,
  original_file_url text,
  resume_text text,
  file_scan_json jsonb,
  upload_sha256 text,
  stripe_checkout_session_id text unique,
  result_json jsonb,
  generated_files_json jsonb not null default '{}'::jsonb,
  failure_reason text,
  email_message_id text,
  processing_started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  full_name text,
  role text not null default 'owner',
  password_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.queue_jobs (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  order_id uuid references public.orders(id) on delete cascade,
  status text not null default 'queued' check (status in ('queued', 'processing', 'retryable', 'completed', 'failed')),
  attempts integer not null default 0,
  payload_json jsonb not null default '{}'::jsonb,
  qstash_message_id text,
  last_error text,
  run_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.error_events (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  severity text not null default 'error',
  message text not null,
  order_id uuid references public.orders(id) on delete set null,
  queue_job_id uuid references public.queue_jobs(id) on delete set null,
  context_json jsonb not null default '{}'::jsonb,
  stack text,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_email text,
  action text not null,
  target_type text,
  target_id text,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

DROP TRIGGER IF EXISTS orders_set_updated_at ON public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

DROP TRIGGER IF EXISTS admin_users_set_updated_at ON public.admin_users;
create trigger admin_users_set_updated_at
before update on public.admin_users
for each row
execute function public.set_updated_at();

DROP TRIGGER IF EXISTS queue_jobs_set_updated_at ON public.queue_jobs;
create trigger queue_jobs_set_updated_at
before update on public.queue_jobs
for each row
execute function public.set_updated_at();

create index if not exists idx_orders_status_created_at on public.orders(status, created_at);
create index if not exists idx_orders_email on public.orders(email);
create index if not exists idx_orders_access_token on public.orders(access_token);
create index if not exists idx_queue_jobs_status_run_at on public.queue_jobs(status, run_at);
create index if not exists idx_error_events_created_at on public.error_events(created_at desc);
create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);

-- Example admin seed. Replace the password hash with one generated by scripts/hash-admin-password.mjs
-- insert into public.admin_users (email, full_name, role, password_hash)
-- values ('owner@example.com', 'Owner', 'owner', 'scrypt$16384$replace_salt$replace_hash')
-- on conflict (email) do update set password_hash = excluded.password_hash, is_active = true;

alter table if exists public.orders add column if not exists file_scan_json jsonb;
alter table if exists public.orders add column if not exists upload_sha256 text;
